### ISSUE TITLE
Marketing layout is missing a float at .pure-menu-heading

### ISSUE THREAD

**Issue by bebraw** [yahoo/pure#499] opened 2015-06-04 06:11 UTC
See http://purecss.io/layouts/marketing/ . It renders `.pure-menu-heading` and `.pure-menu-list` on separate rows in Firefox (same row on Chrome). You can make this consistent by adding `float: left` to `.pure-menu-heading`. After that they'll layout as expected.

**Comment by lkraav** [comment] 2015-06-04 06:38
The whole point of Pure CSS is to avoid flow-breaking floats.

**Comment by bebraw** [comment] 2015-06-04 06:40
@lkraav Ah, good point! Perhaps that `.pure-menu-list` can be modified somehow. Get rid of its float using some other method.

**Comment by jamesalley** [comment] 2015-06-08 21:42
Duplicate of https://github.com/yahoo/pure-site/issues/246

**Closed by jamesalley** 2015-06-08 21:42 UTC
