### ISSUE TITLE
Horizontal-to-Scrollable Menu - firefox 35 shows scroll bar when menu tucked away

### ISSUE THREAD

**Issue by mcbmcb0** [yahoo/pure#439] opened 2015-02-16 07:36 UTC
loving the new responsive menu examples, but for  [horizontal to scrollable menu] 
(http://stage.purecss.io/layouts/tucked-menu/#) on firefox 35 the scrollbar is always visible when the menu is tucked away. however its is inactive until then menu is shown.
win7-64. not that you'd ever have a small screen on a desktop but...
keep up the great work
![responsive](https://cloud.githubusercontent.com/assets/7244003/6208296/fd28afbe-b61a-11e4-82d1-42e54b11d1cf.jpg)

**Comment by jamesalley** [comment] 2015-02-17 21:33
Thanks for the bug report. I was unaware of this behavior in FF Win. This is a new concept, and it's difficult to get it to degrade nicely in older browsers and to work consistently across the latest browsers and with all input methods. For instance, I added some margin knowing that some browsers would display scrollbars when the area is being scrolled; but I didn't notice FF Win would display the scrollbars at all times.

I'm not sure yet how to improve the example to prevent this. Sure, it's just an example to inspire, a starting point for your own ideas, but if it's possible to rectify this, we should. I'll leave this open as a bug.

**Comment by jamesalley** [comment] 2015-02-17 21:40
I think I have a simple fix for this. I'm testing it now.

**Comment by jamesalley** [comment] 2015-02-17 23:07
The fix is in on [http://stage.purecss.io](http://stage.purecss.io): 

```
 .pure-menu-horizontal.custom-menu-tucked {
        z-index: -1;
        top: 45px;
        position: absolute;
        overflow: hidden; /* <–– the fix   */
    }
```

**Closed by jamesalley** 2015-02-17 23:07 UTC
Labels: bug

**Comment by mcbmcb0** [comment] 2015-02-18 03:20
awesome - works well. thank you.
however i note no scroll bar shows on chrome (win7 32) and i think this problem preceded the fix above. too many browsers!
![clipboard01423432243](https://cloud.githubusercontent.com/assets/7244003/6241870/e82079ba-b789-11e4-81fa-983af3a072e5.jpg)

**Comment by jamesalley** [comment] 2015-02-18 03:47
No scrollbars in WebKit/chrome: that's by design.

**Comment by mcbmcb0** [comment] 2015-02-18 03:54
is that a chrome thing or could you say why?
