### ISSUE TITLE
It is not working on firefox 38.0.1

### ISSUE THREAD

**Issue by lujianmei** [yahoo/pure#491] opened 2015-05-19 09:56 UTC
I checked the demo on official website, and found that these example pages not ok on my firefox, following is a example you can try:
http://purecss.io/layouts/pricing/
I also tried my Samsung firefox, it is also not working correctly, especially these responsive page, and using 0.6 pure-min.css.

**Comment by Dumbaz** [comment] 2015-05-19 11:24
Working for me. Had to unblock scripts, and allow remote requests from Tubmlr for the image and yahooapis for the css. The error might be on your side.

**Comment by jamesalley** [comment] 2015-05-19 17:28
Thanks for the bug report, but the details are too thin to act upon. What version of FF are you using, and on what platform? What specifically is failing for you? An annotated screenshot may help illustrate the problems you're seeing. Then we'll all perhaps be able to reproduce it and address the problem.

**Comment by adbutterfield** [comment] 2015-06-15 07:20
I'm also having an issue with Firefox and the landing page demo. The title on the left, and navigation links on the right should be inline, but for some reason, the links on the right drop onto a new line (see attached screen shot).
Defect is present in:
Firefox: 38.0.5
Firefox Developer Edition: 40.0a2 (2015-06-09)
![screen shot 2015-06-15 at 4 14 59 pm](https://cloud.githubusercontent.com/assets/4752047/8154934/1af40b1c-137a-11e5-829a-eb74382fdd3c.png)

**Comment by LeeDotP** [comment] 2015-10-09 15:21
I am not 100% sure but I think this has to do with an update to Firefox no longer recognizing old flexbox property in the .pure-g class. Hope this helps.

Go into the class and change it from 

display: -webkit-flex;
-webkit-flex-flow: row wrap;

to 

display: -webkit-box;
  display: -webkit-flex;
  display: flex;
  -webkit-flex-flow: row wrap;
      -ms-flex-flow: row wrap;
          flex-flow: row wrap;

**Comment by redonkulus** [comment] 2016-12-19 20:46
This should be fixed with release 0.6.1 since we use post-css to add the browser prefixes now. Plus I do not see this issue in Firefox on http://purecss.io/layouts/pricing/ anymore.

**Closed by redonkulus** 2016-12-19 20:46 UTC
Labels: needs info
