### ISSUE TITLE
Sass Port?

### ISSUE THREAD

**Issue by nicekiwi** [yahoo/pure#501] opened 2015-06-10 00:01 UTC
An scss compatible port would be pretty awesome, let you setup custom grid variables etc.

**Comment by afrische** [comment] 2015-07-23 19:16
Duplicate of #68

**Closed** 2015-07-25 19:13 UTC

**Comment by MarkehMe** [comment] 2015-08-12 12:43
Decided I'd make this which converts the latest Pure.css into Sass..

https://github.com/MarkehMe/sassinate-pure

Here it is if you'd like it: https://github.com/MarkehMe/pure-sass
