### ISSUE TITLE
Buttons with icons example is broken in the docs

### ISSUE THREAD

**Issue by ShashankaNataraj** [yahoo/pure#634] opened 2017-02-23 04:13 UTC
https://purecss.io/buttons/ has an example for buttons with icons. The buttons do get shown but no icons are shown because the font awesome css file referenced is http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css which seems to be broken when the docs page loads it, but loads when I open it in an independent tab?

**Comment by guest20** [comment] 2017-02-27 10:56
![image](https://cloud.githubusercontent.com/assets/3603869/23358797/ac86df74-fce3-11e6-9993-3588bcdb85c4.png)

**Comment by axelhahn** [comment] 2017-02-27 17:22
The problem is mixing https and http (pure-css-website is https and tries to connect a CDN over unencrypted http - this is blocked by the webbrowser).
What I see is:
http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css works
and
https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css works
work and point to the same.

@yahoo: the fix is
OLD:
<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
NEW:
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

(maybe there is a newer version too)

**Comment by redonkulus** [comment] 2017-02-27 18:22
Thanks everyone for the report, this is fixed now https://purecss.io/buttons/

We had recently moved the site to https and we didn't fix all the URLs.

**Closed by redonkulus** 2017-02-27 18:22 UTC
