### ISSUE TITLE
Make .pure-u-1 and other 100% bases overrideable by floating them higher in the stylesheet

### ISSUE THREAD

**Issue by lkraav** [yahoo/pure#437] opened 2015-02-11 15:39 UTC
There are use cases where it makes sense for automation (read: WordPress column shortcode type stuff) to always stick .pure-u-1 into base output, but let the user append additional classes as he sees fit on a case by case basis. Meaning the automated rule cannot easily be removed by hand. Hence we get

```
<div class="pure-u-1 pure-u-1-3 pure-u-md-2-5">
    ...
</div>
```

Order of classes presented in the element attribute doesn't matter. Only stylesheet order matters. As previous releases, 0.6.0-rc-1 still has .pure-u-1 at the bottom of the stylesheet.

https://github.com/yahoo/pure-release/blob/master/grids-units.css#L212

I think even without my presented use case, fundamental cascading logic supports adjusting the rule order and floating 100% rules up top, making it possible to override them however.

I looked at the pure rework plugin index.js code and my head started to hurt. Too much at the moment for me to try to understand how to create a pull request for this.

@jamesalley and @ericf what are your thoughts here on the concept?

**Comment by jamesalley** [comment] 2015-02-11 19:54
Don't worry about a PR at this point-- discussion is also good. 

The rework plugin for grids might seem daunting at first, but it's purpose is pretty straightforward: it's designed so that you can set up a config (with, for example, exactly what breakpoints you want your grid to follow for sm, md, lg, etc.) and then a custom responsive grids file is generated for you. 

Now to the core issue at hand. I see your point, but I want to think about it a bit. Moving that ruleset to the top of the file might have unintended consequences going the other direction. Maybe it's good pure-u-1 trumps all others. Let me think about it.

I can tell you right now, though, that I'm leaning towards a verdict of "no change is warranted." It seems like this is a problem caused by a quirk of another system, and that other system is where the problem should be addressed.

**Comment by lkraav** [comment] 2015-02-11 20:08
Hmmm, I think I am actually able to work around this with regexing the incoming class list. If I detect pure-u-[0-9], then skip the default pure-u-1 class. Thanks for getting back to me, it triggered the next right step for me.

I agree there may be side-effects to consider. But pure so far hasn't really concerned itself with backwards compatibility and it's been right to do so. 0.6.0, or at least the RC-s, would be a great place to give it a shot and roll it back if complaints are heard. I'd really like to know what exactly breaks because of this change, too. Like said before, fundamentally the rule float seems a sound decision - starting with base and going towards granular, instead of the other way around.

**Comment by jamesalley** [comment] 2015-02-11 21:54
I'm going to leave this issue open for discussion, because in Q2 I should be taking another look at Grids, and that would be the best time to introduce such a change. For 0.6.0, I've already publicized that Grids have not changed _at all_, and I would hate to force people to QA all their grids layouts due to this one tiny change. Who knows, maybe someone else for some reason outputs `pure-u-1-4` by default? In this case it's difficult to make assumptions about what the "base" case might be, although assuming "full width" as base does make sense to me, given that all other units are fractions. But only marginally so.

In any event, ideally you should keep things DRY by only outputting the correct class in the first place, instead of trying to override `pure-u-1`. I will consider this change in order when working on grids in Q2.

**Comment by redonkulus** [comment] 2016-12-20 04:22
Feel free to continue the discussion but closing the issue.

**Closed by redonkulus** 2016-12-20 04:22 UTC
Labels: discussion
