### ISSUE TITLE
Add a distribution as css-modules (like in given repo) ?

### ISSUE THREAD

**Issue by fabm22** [yahoo/pure#540] opened 2015-12-29 02:23 UTC
Hi.

Wouldn't it be a good thing to also add an export of the modules provided by pure as (actual) **css-modules** like somebody already did in this repo here :  https://github.com/StevenIseki/pure-css ?

Would it make sense or does css-modules appear as too "young" maybe ?

_( For those who don't know what css-modules are, it solves some of the historical more well known problems of css stylesheets, particularly by removing the global nature/scope of css rules and styles:  https://github.com/css-modules/css-modules  )_

**Comment by redonkulus** [comment] 2016-11-22 05:26
Make sense, also a duplicate of https://github.com/yahoo/pure/issues/565

**Closed by redonkulus** 2016-11-22 05:26 UTC
